Do not pass connection name to `PrimaryReadReplicaConnection::connect()`
doctrine/migrations pull request #1156
Opened 2021-04-28 12:07 UTC by frankverhoeven

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #1154 #1155 

#### Summary

Passing a connection name to `PrimaryReadReplicaConnection::connect()` will result in an exception being thrown.
This change will remove the `master` name from `TableMetadataStorage::isInitialized()` to prevent that exception.

2021-04-28 12:15 UTC, stof requested changes

2021-04-28 12:15 UTC, stof commented on lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php
> +            $this->connection->connect();
The equivalent of the old `->connect('master')` API of MasterSlaveConnection is `->ensureConnectedToPrimary()`, not `->connect()`

2021-04-28 14:54 UTC, stof approved these changes

2021-04-29 21:17 UTC, SenseException approved these changes

2021-04-30 11:01 UTC, greg0ire commented
Should this target 2.3.x, or does the fix not apply there?

2021-04-30 13:04 UTC, stof commented
@greg0ire no. 2.3.x is not affected. It properly uses the new API for the new version of DBAL already (but `TableMetadataStorage` does not exist at all in 2.3.x so a merge up did not fix it for 3.x)

2021-04-30 13:40 UTC, merged

2021-04-30 13:41 UTC, greg0ire commented
Let's merge this then! Thanks @frankverhoeven !