TableMetadataStorage - fix isAlreadyV3Format for the same version values
doctrine/migrations pull request #1466
Opened 2024-10-24 07:44 UTC by kfrankiewicz

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | no link, the explanation below

#### Summary

`Doctrine\Migrations\Metadata\Storage\TableMetadataStorage::isAlreadyV3Format()` method was returning `false` even if the both versions in the arguments have exactly the same value. E.g.:

```
       strpos(
            'Namespace\Version1234',
            'Namespace\Version1234'
        ) !== (
                strlen('Namespace\Version1234') -
                strlen('Namespace\Version1234')
            );
```
Compares `0 !== 0` what gives false, but `isAlreadyV3Format()` should return `true` when the versions are the same.

2024-10-24 08:35 UTC, greg0ire approved these changes

2024-10-24 22:14 UTC, SenseException requested changes
Thank you. 

I'd expect a test that covers the fixed behaviour.

2024-11-06 13:09 UTC, kfrankiewicz commented
@SenseException Thanks for asking for the test. There was an issue! I've added the test.

2024-11-06 19:32 UTC, greg0ire commented
It seems there are CI jobs failing. Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to handle those.

2024-11-07 09:23 UTC, kfrankiewicz commented
Done @greg0ire. Hope I haven't missed anything more.

2024-11-11 22:58 UTC, SenseException approved these changes

2024-11-12 21:44 UTC, merged

2024-11-12 21:44 UTC, greg0ire commented
Thanks @kfrankiewicz